version: "3.8"
services:
  who-is-at-home:
    image: "garfieldz.azurecr.io/rpi-api-server:12e059f"
    user: nobody
    ports:
      - "127.0.0.1:9099:9099"
    restart: unless-stopped
    environment:
      PLUGIN_NAME: "ishome"
      LISTEN_ADDR: ":9099"
      PUSH_SERVICE: "ifttt"
      WHOISATHOME_USERS: ""
      IFTTT_KEY: ""
      IFTTT_EVENT_NAME: ""
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
  temperature:
    image: "garfieldz.azurecr.io/rpi-api-server:12e059f"
    user: nobody
    ports:
      - "127.0.0.1:9098:9098"
    restart: unless-stopped
    environment:
      PLUGIN_NAME: "temperature"
      LISTEN_ADDR: ":9098"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
  network:
    image: "garfieldz.azurecr.io/rpi-api-server:4fbbe94"
    user: nobody
    ports:
      - "127.0.0.1:9097:9097"
    restart: unless-stopped
    environment:
      PLUGIN_NAME: "networkavailability"
      LISTEN_ADDR: ":9097"
      ProxyUrl: "http://rpi:1080"
    extra_hosts:
      - "rpi:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
